m4_define_macros += -D minivos_version="$(shell cat VERSION)"
m4_define_macros += -D minivos_build_time="$(shell date)"
m4_define_macros += -D ENV_LISTEN_IP="$(ENV_LISTEN_IP)"
m4_define_macros += -D ENV_PUBLIC_IP="$(ENV_PUBLIC_IP)"
m4_define_macros += -D ENV_UDP_PORT="$(ENV_UDP_PORT)"
m4_define_macros += -D ENV_TCP_PORT="$(ENV_TCP_PORT)"
m4_define_macros += -D ENV_TLS_PORT="$(ENV_TLS_PORT)"
m4_define_macros += -D ENV_WS_PORT="$(ENV_WS_PORT)"
m4_define_macros += -D ENV_DOMAIN_MAIN="$(ENV_DOMAIN_MAIN)"
m4_define_macros += -D ENV_LOG_LEVEL="$(ENV_LOG_LEVEL)"
m4_define_macros += -D ENV_XLOG_LEVEL="$(ENV_LOG_LEVEL)"